## To see all available configs, please check the documentation
## https://github.com/TerraHubCorp/terrahub/tree/master/docs
## project config
project:
  name: 'devopsbootcamp-ead/GitOps'
  code: '6e5c22f0'
  include:
    - '.'
  exclude:
    - '**/.terraform/**'
    - '**/node_modules/**'
    - '**/.git/**'

## terraform config
terraform:
  varFile:
    - 'default.tfvars'
#   var:
#     account_id: 123456789012
#   version: 0.12.16
