apiVersion: apps/v1
kind: Deployment
metadata:
  name: gogs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gogs
  template:
    metadata:
      labels:
        app: gogs

    spec:
      containers:
        - name: gogs
          image: gogs/gogs:latest
         # resources:
         #   requests:
         #     memory: "5Mi"
         #     cpu: "10m"
         #   limits:
         #     memory: "10Mi"
         #     cpu: "20m"
          env:
          - name: USER_UID
            value: "1000"
          - name: USER_GID
            value: "1000"
          ports:
            - name: http-port
              containerPort: 3000
            - name: ssh-port
              containerPort: 22
          volumeMounts:
            - name: gogs-home
              mountPath: /data

      volumes:
        - name: gogs-home
          emptyDir: {}
