apiVersion: v1
kind: Service
metadata:
  name: mattermost
spec:
  type: NodePort
  ports:
    - nodePort: 32115
      port: 8065
      name: http-port
      targetPort: 8065
  selector:
    app: mattermost
