apiVersion: v1
kind: Service
metadata:
  name: gogs
spec:
  type: NodePort
  ports:
    - nodePort: 32113
      port: 3000
      name: http-port
      targetPort: 3000

    - nodePort: 32125
      port: 22
      name: ssh-port
      targetPort: 22
  selector:
    app: gogs
