apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "9"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"extensions/v1beta1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"notifybot"},"name":"notifybot","namespace":"marcpires"},"spec":{"progressDeadlineSeconds":600,"replicas":1,"revisionHistoryLimit":10,"selector":{"matchLabels":{"app":"notifybot"}},"strategy":{"rollingUpdate":{"maxSurge":1,"maxUnavailable":1},"type":"RollingUpdate"},"template":{"metadata":{"labels":{"app":"notifybot"}},"spec":{"containers":[{"image":"us.gcr.io/videocoverterservice/notifybot-marcpires:49f23dd84e077a1f83bbe0156b87f2aafd55fd5d","imagePullPolicy":"IfNotPresent","livenessProbe":{"failureThreshold":3,"httpGet":{"path":"/notify/healthz","port":8080,"scheme":"HTTP"},"initialDelaySeconds":10,"periodSeconds":10,"successThreshold":1,"timeoutSeconds":5},"name":"notifybot","ports":[{"containerPort":8080}],"readinessProbe":{"failureThreshold":3,"httpGet":{"path":"/notify/healthz","port":8080,"scheme":"HTTP"},"periodSeconds":10,"successThreshold":1,"timeoutSeconds":1},"resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","volumeMounts":[{"mountPath":"/data/symphony/notifybot/config.json","name":"bot-config","subPath":"config.json"},{"mountPath":"/data/symphony/notifybot/certs","name":"secrets","readOnly":true},{"mountPath":"/data/symhony/notifybot/logs","name":"logs"}]}],"dnsPolicy":"ClusterFirst","restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"terminationGracePeriodSeconds":30,"volumes":[{"configMap":{"name":"notifybot-config-marcpires"},"name":"bot-config"},{"name":"secrets","secret":{"secretName":"notifybot-dev-certs-marcpires"}},{"emptyDir":{},"name":"logs"}]}}}}
  creationTimestamp: 2019-06-19T19:13:59Z
  generation: 9
  labels:
    app: notifybot
  name: notifybot
  namespace: marcpires
  resourceVersion: "575001"
  selfLink: /apis/extensions/v1beta1/namespaces/marcpires/deployments/notifybot
  uid: 640eca53-92c6-11e9-b932-42010a800105
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: notifybot
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: notifybot
    spec:
      containers:
      - image: us.gcr.io/videocoverterservice/notifybot-marcpires:49f23dd84e077a1f83bbe0156b87f2aafd55fd5d
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /notify/healthz
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        name: notifybot
        ports:
        - containerPort: 8080
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /notify/healthz
            port: 8080
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /data/symphony/notifybot/config.json
          name: bot-config
          subPath: config.json
        - mountPath: /data/symphony/notifybot/certs
          name: secrets
          readOnly: true
        - mountPath: /data/symhony/notifybot/logs
          name: logs
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: notifybot-config-marcpires
        name: bot-config
      - name: secrets
        secret:
          defaultMode: 420
          secretName: notifybot-dev-certs-marcpires
      - emptyDir: {}
        name: logs
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: 2019-06-19T19:13:59Z
    lastUpdateTime: 2019-06-19T19:13:59Z
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: 2019-06-19T19:13:59Z
    lastUpdateTime: 2019-06-20T21:18:31Z
    message: ReplicaSet "notifybot-667c8d77df" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 9
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1

