apiVersion: apps/v1
kind: Deployment
metadata:
  name: friday
spec:
  replicas: 1
  template:
    metadata: 
      labels:
        name: friday
        app: friday
    namespace: default
    spec:
     selector:
       matchLabels:
         app: friday
      containers:
        - name: friday
          image: testdriveninfra/friday:1.0.2
          resources:
            requests: 
              cpu: 20m
              memory: 50Mi
            limits:
              cpu: 20m
              memory: 30Mi



