apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: figlet
  annotations:
    fluxcd.io/automated: "true"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: figlet
        app: figlet
    namespace: default
    spec:
      containers:
        - name: figlet
          image: testdriveninfra/figlet:1.0.0
          resources:
            requests: 
              cpu: 20m
              memory: 50Mi
            limits:
              cpu: 20m
              memory: 30Mi



