apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: root-application-set
  namespace: argocd
spec:
  generators:
  - matrix:
      generators:
      - git:
          repoURL: https://github.com/marcpires/gitops.git
          revision: HEAD
          directories:
           - path: envs/*
  template:
      metadata:
        name: '{{path.basename}}-{{name}}'
      spec:
        project: default #Can be set in application metadata.labs.environment

        #Application source
        source:
          repoURL: "https://github.com/marcpires/gitops.git"
          targetRevision: HEAD
          path: '{{path}}'
        
        # Destination  
        destination:
          server: https://kubernetes.default.svc
          namespace: '{{path.basename}}'

        syncPolicy:
          syncOptions:
            - CreateNamespace=true
          automated:
            prune: true
            selfHeal: true
  