---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mattermost
    version: preview
  name: mattermost
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.mattermost: semver:~5.14
    #fluxcd.io/ignore: true
    #fluxcd.io/locked: true
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mattermost
  template:
    metadata:
      labels:
        app: mattermost

    spec:
      containers:
      - name: mattermost
        image: mattermost/mattermost-preview:5.18.0-rc1
         # resources:
         #   requests:
         #     memory: "5Mi"
         #     cpu: "10m"
         #   limits:
         #     memory: "10Mi"
         #     cpu: "20m"
        env:
        - name: USER_UID
          value: "1000"
        - name: USER_GID
          value: "1000"
        ports:
        - name: http-port
          containerPort: 8065
        volumeMounts:
        - name: mattermost-home
          mountPath: /data

      volumes:
      - name: mattermost-home
        emptyDir: {}
